title: kdg391
description: > # this means to ignore newlines until "baseurl:"
  It's me
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kdg391.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'

# Profile information
name: kdg391
tagline: Student Developer
about-description: # Add Discription
pic: python.webp # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website
github: kdg391 # Add your Github handle
instagram: # Add your Twitter handle

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
